"""empty message

Revision ID: 6e67136e8952
Revises: 097d5514d25f
Create Date: 2022-04-20 15:25:58.982422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e67136e8952'
down_revision = '097d5514d25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('company', sa.String(length=140), nullable=False),
    sa.Column('date_applied', sa.String(length=140), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('in_process', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applied_jobs')
    # ### end Alembic commands ###
